- type: job
  id: CitizenDSM
  name: Imperial Citizen
  description: A inhabitant of the Taypani Sector
  playTimeTracker: JobFreeholderDSM
  weight: 18
  startingGear: FreeholderGear
  requirements:
    - !type:FactionRequirement
        factionID: "DSM"
  alwaysUseSpawner: true
  icon: "JobIconImperialFreeholder"
  requireAdminNotify: false
  supervisors: job-supervisors-imperial 
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: FreeholderGear
  equipment:
    id: FreeholderPDA
    ears: ClothingHeadsetEmpireCiv
    pocket1: ImperialPassportBareLegit