- type: job
  id: TemplarDSM
  name: job-name-advocatustemplar
  description: job-description-advocatustemplar
  playTimeTracker: JobTemplarDSM
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 55000
    - !type:SpeciesRequirement
      allowedOnly:
        - Human
    - !type:SexRequirement
      allowed:
        - Male
    - !type:FactionRequirement
      factionID: "DSM"
  weight: 22
  startingGear: TemplarGear
  alwaysUseSpawner: true
  icon: "JobIconAdvocatusTemplar"
  requireAdminNotify: false
  supervisors: job-supervisors-imperial
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-templar
  access:
  - Command
  - Empire
  - Maintenance
  - Advocatus
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: TemplarGear
  equipment:
    id: TemplarPDA
    ears: ClothingHeadsetEmpire
    neck: ClothingNeckCloakInspector
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsGlovesImperialLonggloves
    pocket1: ImperialPassportBareLegit
