- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  setPreference: false # Frontier
  startingGear: PassengerGear
  icon: "JobIconPassenger"
#  supervisors: job-supervisors-everyone
  accessGroups:
  - GeneralAccess

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
