- type: job
  id: KapitanNCWL
  name: job-name-kapitan
  description: job-description-kapitan
  playTimeTracker: JobKapitanNCWL
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 50000
    - !type:FactionRequirement
      factionID: "NCWL"
  weight: 25
  startingGear: KapitanGear
  alwaysUseSpawner: true
  icon: "JobIconCommsOfficer"
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-kapitan
  access:
  - Command
  - Maintenance
  - Service
  - External
  - NCWLGeneral
  - NCWLJail
  - NCWLCommand
  - NCWLArmory
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: KapitanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNCWL
    back: ClothingBackpackNCWLFilledSanitar
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatNCWLBeret
    outerClothing: ClothingOuterArmorNCWLCarapaceKapitan
    id: KapitanPDA
    ears: ClothingHeadsetNCWL
    belt: ClothingBeltNCWLWebbing
    pocket1: WeaponPistolHKUSP
    pocket2: NCWLPassportAccepted
    gloves: ClothingHandsGlovesFingerless
  # duffelbag: ClothingBackpackDuffelNCWLFilledSanitar YAMLFIX: This doesn't go here anymore.
  # satchel: ClothingBackpackSatchelNCWLFilledSanitar
