- type: job
  id: MarshalCMM
  name: job-name-marshal
  description: job-description-marshal
  playTimeTracker: JobMarshalCMM
  requirements:
    - !type:WhitelistRequirement
    - !type:FactionRequirement
        factionID: "TSP"
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-marshallie
  weight: 39
  startingGear: MarshalGear
  alwaysUseSpawner: true
  icon: "JobIconMarshal"
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm 
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Minuteman
  - MinutemanPrison
  - MinutemanRankingOfficer
  - MinutemanMarshal
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: MarshalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMMOfficer
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatCMMMarshal
    gloves: ClothingHandsGlovesCombat
    belt: WeaponRevolverSnubnose
    id: MarshalPDA
    ears: ClothingHeadsetCMM
    outerClothing: ClothingOuterArmorCMMCarapace